### PR TITLE
improve contet2D create/get/put ImageData method

### PR DESCRIPTION
**Pull request by drelaptop**
在基础上完善：https://github.com/cocos-creator-packages/jsb-adapter/pull/55

- 测试

```JavaScript
//绘制矩形区
var imageData = ctx.createImageData(width, height)
// 在 ImageData 下半部分添加颜色
for (var i = 0; i < width; i += 1) {
    for (var j = height/2; j < height; j += 1) {
        var index = (j * width + i) * 4;
        imageData.data[index + 0] = i;
        imageData.data[index + 1] = Math.floor((i + j) / 2);
        imageData.data[index + 2] = j;
        imageData.data[index + 3] = 255;
    }
}
// 将颜色块，放到指定位置
ctx.putImageData(imageData, width/4, height / 4, 0, height / 2, width/4, height / 2);
imageData = ctx.getImageData(0, 0, width, height);
let success = jsb.saveImageData(imageData.data, width, height, filePath); 
```

- png 图片

render_to_sprite_image

### CODE REVIEW

**Comment by drelaptop** [comment]
@pandamicro please review and merge

**Comment by drelaptop** [comment]
please review or merge @pandamicro @jareguo

**Comment by drelaptop** [comment]
please review and merge @minggo

**Comment by minggo** [comment]
这个仓库我没合并权限，@pandamacro

**Comment by drelaptop** [comment]
麻烦 review 合并 @pandamicro

**Pull request merged**
